export { useDashboard } from './hooks/use-dashboard'
export { StatCard } from './components/stat-card'
export { Indicators } from './components/indicators'
export { DailyEvolutionChart } from './components/daily-evolution-chart'
export { ExpensesByCategoryChart } from './components/expenses-by-category-chart'
export { IncomeVsExpensesChart } from './components/income-vs-expenses-chart'
export { ExpensesByPaymentMethodChart } from './components/expenses-by-payment-method'
export { MonthlyComparisonChart } from './components/monthly-comparison-chart'
export { SpendingHeatmap } from './components/spending-heatmap'
export { RecentMovements } from './components/recent-movements'
export { DashboardSkeleton } from './dashboard-skeleton'
export { DashboardCustomize, DASHBOARD_SECTIONS } from './components/dashboard-customize'
